name: Build and Release

on:
  push:
    branches:
      - main  # 可以根据你的分支名进行调整

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate Change Log
      id: changelog
      run: |
        # Get the latest commit messages as the Change Log
        CHANGELOG=$(git log --pretty=format:"%s" -n 10)
        echo "::set-output name=changelog::$CHANGELOG"

    - name: Zip PPTX files
      run: |
        cd "ppt 16-9"
        zip -r pptx.zip *.pptx

    - name: Zip Lyrics files
      run: |
        cd "lyrics"
        zip -r lyrics.zip *
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Upload PPTX ZIP to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "ppt 16-9/pptx.zip"
        asset_name: pptx.zip
        asset_content_type: application/zip

    - name: Upload Lyrics ZIP to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "lyric/lyrics.zip"
        asset_name: lyrics.zip
        asset_content_type: application/zip
